image: docker:latest
services:
  - docker:dind

before_script:
  - export GRADLE_USER_HOME=`pwd`/gradle

cache:
  paths:
    - gradle/wrapper
    - gradle/caches

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - docker-login
  - build

docker-login:
  stage: docker-login
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - ./gradlew build jib -Djib.to.auth.username=gitlab-ci-token -Djib.to.auth.password=$CI_BUILD_TOKEN

