rootProject.name = "Spring Boot Integrations"

include("spring-boot-activemq-integration",
        "spring-boot-activemq-integration:spring-activemq-consumer",
        "spring-boot-activemq-integration:spring-activemq-consumer-two",
        "spring-boot-activemq-integration:spring-activemq-producer",
        "spring-boot-cache-integration",
        "spring-boot-graphql-integration",
        "spring-boot-hibernate-integration",
        "spring-boot-hibernate-locking",
        "spring-boot-https-integration",
        "spring-boot-jdbc-integration",
        "spring-boot-jpa-integration",
        "spring-boot-kafka-integration",
        "spring-boot-multipart-integration",
        "spring-boot-pdf-integration",
        "spring-boot-redis-integration",
        "spring-boot-sftp-file-integration",
        "spring-boot-swagger-integration",
        "spring-boot-hibernate-dynamic-filter-integration",
        "spring-boot-hibernate-dynamic-model-integration",
        "spring-boot-input-validation-integration")
