server:
  port: 9013
spring:
  h2:
    console:
      enabled: true


security.datasource.jdbc-url: jdbc:mysql://localhost:3306/spring_security_demo_bcrypt?useSSL=false&serverTimezone=UTC
security.datasource.username: springstudent
security.datasource.password: springstudent

