INSERT INTO PERSON(ID,NAME,STATUS) VALUES (1,'Ram','NEW');
INSERT INTO PERSON(ID,NAME,STATUS) VALUES (2,'Vijay','NEW');
INSERT INTO PERSON(ID,NAME,STATUS) VALUES (3,'Ganesan','NEW');
INSERT INTO PERSON(ID,NAME,STATUS) VALUES (4,'Saradha','NEW');
