spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
