server:
  port: 9004

spring:
  application:
    name: 'spring-jpa-hibernate-locking'
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=Var_Integration_Demo_IT
    username: demouser
    password: sup3rSEC
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.SQLServer2012Dialect

